//Index
export const GET_MOST_POPULAR_MOVIE = "FETCH_MOVIE";
export const GET_POPULAR_MOVIES = "FETCH_MOVIE_REVIEWS";
export const GET_UPCOMING_MOVIES = "FETCH_CAST";
export const GET_TOP_RATED_MOVIES = "FETCH_VIDEOS";
export const GET_LATEST_MOVIES = "FETCH_SIMILAR_MOVIES";

//Header
export const FETCH_TRAILER = "FETCH_TRAILER";

//Search
export const FETCH_RESULTS = "FETCH_RESULTS";
export const FETCH_TOTAL_RESULTS = "FETCH_TOTAL_RESULTS";
export const NEXT_PAGE = "NEXT_PAGE";

//ActorSummary
export const FETCH_PERSON = "FETCH_PERSON";
export const FETCH_MOVIE_CREDITS = "FETCH_MOVIE_CREDITS";

//MovieSummary
export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_MOVIE_REVIEWS = "FETCH_MOVIE_REVIEWS";
export const FETCH_CAST = "FETCH_CAST";
export const FETCH_VIDEOS = "FETCH_VIDEOS";
export const FETCH_SIMILAR_MOVIES = "FETCH_SIMILAR_MOVIES";
